# These keybindings usually work on laptops.

# Brightness control with brightnessctl
bindd = , XF86MonBrightnessUp, Increase screen brightness, exec, brightnessctl set +1%
bindd = , XF86MonBrightnessDown, Decrease screen brightness, exec, brightnessctl set 1%-

# Volume control with wpctl, package from wireplumber
bindeld = , XF86AudioRaiseVolume, Increase volume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+
bindeld = , XF86AudioLowerVolume, Decrease volume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bindld = , XF86AudioMute, Toggle audio mute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# playerctl for media control
bindld = , XF86AudioPlay, Media play/pause, exec, playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, playerctl previous
bindld = , XF86AudioNext, Next track, exec, playerctl next
