# This file only contains the keybindings for 3rd party applications

$key = TAB
$modifier = ALT
$modifier_release = ALT_L
$reverse = SHIFT

# Define the applications to be used
$terminal = kitty
$fileManager = kitty -e yazi /home/$USER

# Define the scripts to be used
$application_launcher = qs -c ummitos ipc call launcher apps
$clipboard_manager = qs -c ummitos ipc call launcher clipboard
$wallpaper_picker = qs -c ummitos ipc call wallpaper toggle
$color_picker = bash ~/script/hypr/hyprpicker/hyprpicker.sh
$lock_screen = hyprlock

# binding the programs to the keys
bind = $mainMod, T, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, 36, exec, $application_launcher
bind = $mainMod, X, exec, qs -c ummitos ipc call session toggle
bind = $mainMod, L, exec, $lock_screen
bind = ALT_L, V, exec, $clipboard_manager
bind = ALT_L, W, exec, $wallpaper_picker
bind = ALT_L, E, exec, smile
bind = ALT_L, P, exec, $color_picker
bind = ALT_L, O, exec, woomer
bind = $mainMod Shift, 36 , exec, kitty -e  ~/script/waybar/update.sh

# HyprShot <- https://github.com/Gustash/Hyprshot
bind = $mainMod, PRINT, exec, hyprshot -m window
bind = , PRINT, exec, hyprshot -m output
bind = $shiftMod, PRINT, exec, hyprshot -m region -z
