general {
    lock_cmd = qs -c ummitos ipc call lock lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = bash ~/script/hypr/lock/detect_vm.sh
}
